import { useEffect, useState } from 'react';
import axios from 'axios';
import { FaArrowLeft, FaMapMarkerAlt, FaUserFriends } from 'react-icons/fa';
import { useNavigate, useParams } from 'react-router-dom';
import { getAvatarUrl, getInitialAvatarUrl } from '../../utils/imageUrl';
import './PublicProfilePage.css';
import './PublicProfileContent.css';

const auth = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } });

export default function PublicProfilePage() {
    const { id } = useParams(); const navigate = useNavigate();
    const [profile, setProfile] = useState(null); const [posts, setPosts] = useState([]); const [friends, setFriends] = useState([]); const [activeTab, setActiveTab] = useState('posts'); const [error, setError] = useState('');
    useEffect(() => { let active = true; Promise.all([axios.get(`/api/users/public/${id}`, auth()), axios.get(`/api/posts/user/${id}`, auth()), axios.get(`/api/users/public/${id}/friends`, auth())]).then(([profileResponse, postsResponse, friendsResponse]) => { if (active) { setProfile(profileResponse.data); setPosts(postsResponse.data.posts || []); setFriends(friendsResponse.data.friends || []); } }).catch((requestError) => { if (active) setError(requestError.response?.data?.message || 'Không thể tải hồ sơ.'); }); return () => { active = false; }; }, [id]);
    if (error) return <main className="public-profile-state"><button type="button" onClick={() => navigate(-1)}><FaArrowLeft /> Quay lại</button><p>{error}</p></main>;
    if (!profile) return <main className="public-profile-state">Đang tải hồ sơ…</main>;
    const displayName = profile.fullName || profile.username;
    return <main className="public-profile-page"><section className="public-profile-card"><button type="button" className="public-profile-back" onClick={() => navigate(-1)}><FaArrowLeft /> Quay lại</button><div className="public-profile-cover" style={profile.coverImage ? { backgroundImage: `url(${getAvatarUrl(profile.coverImage)})` } : undefined} /><div className="public-profile-main"><img className="public-profile-avatar" src={getAvatarUrl(profile.avatar, profile.username)} alt={`Avatar ${displayName}`} onError={(event) => { event.currentTarget.src = getInitialAvatarUrl(profile.username); }} /><div><p className="public-profile-label"><FaUserFriends /> Bạn bè trên ChatWave</p><h1>{displayName}</h1><p>@{profile.username}</p></div></div><div className="public-profile-info">{profile.gender && <span>Giới tính: {profile.gender}</span>}{profile.country && <span><FaMapMarkerAlt /> {profile.country}</span>}<span className={profile.status === 'online' ? 'online' : ''}>{profile.status === 'online' ? 'Đang hoạt động' : 'Ngoại tuyến'}</span></div><nav className="public-profile-tabs"><button className={activeTab === 'posts' ? 'active' : ''} onClick={() => setActiveTab('posts')}>Bài viết ({posts.length})</button><button className={activeTab === 'friends' ? 'active' : ''} onClick={() => setActiveTab('friends')}>Bạn bè ({friends.length})</button><button className={activeTab === 'about' ? 'active' : ''} onClick={() => setActiveTab('about')}>Giới thiệu</button></nav></section><section className="public-profile-content">{activeTab === 'posts' && <div className="public-post-list">{posts.length ? posts.map((post) => <article className="public-post" key={post.id}>{post.content && <p>{post.content}</p>}{post.image && <img src={getAvatarUrl(post.image)} alt="Ảnh bài viết" />}</article>) : <p className="public-empty">Chưa có bài viết.</p>}</div>}{activeTab === 'friends' && <div className="public-friends-grid">{friends.length ? friends.map((friend) => <button type="button" key={friend.id} onClick={() => navigate(`/profile/${friend.id}`)}><img src={getAvatarUrl(friend.avatar, friend.username)} alt="" onError={(event) => { event.currentTarget.src = getInitialAvatarUrl(friend.username); }} /><span>{friend.fullName || friend.username}<small>{friend.status === 'online' ? 'Đang hoạt động' : 'Ngoại tuyến'}</small></span></button>) : <p className="public-empty">Chưa có bạn bè.</p>}</div>}{activeTab === 'about' && <article className="public-about"><h2>Giới thiệu</h2><p>Quốc gia: {profile.country || 'Chưa cập nhật'}</p><p>Giới tính: {profile.gender || 'Chưa cập nhật'}</p></article>}</section></main>;
}
